import Header from "../components/Header"
import Main from "../components/Showcase"
import Head from 'next/head'
export default function Home() {
  return (
     <div className="bg-[#000] w-screen h-screen">
       <Head>
        <title>Oluwasegun Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <Header/>
       <Main/>
     </div>
 
  )
}